// Components
import Footer from "./Components/Footer/page";
import Navbar from "./Components/Navbar/page";

// Font
import { Rubik } from "next/font/google";

// Style
import "./globals.css";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "JOJO LIST | Home",
    template: "JOJO LIST | %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <div className="content">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
