import { Inter } from "next/font/google";
import "./globals.css";

// Components
import Footer from "./Components/Footer/page";
import Navbar from "./Components/Navbar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "JOJO LIST",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
